version: '3.7'

services:
  slave:
    image: meappy/jenkins-php-agent:latest
    environment:
      - JAVA_HOME=${JAVA_HOME:-/opt/bitnami/java}
      - JAVA_OPTS=${JAVA_OPTS}
      - JENKINS_AGENT=${JENKINS_AGENT:-/usr/share/jenkins/slave.jar}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME}
      - JENKINS_AGENT_VERSION=${JENKINS_AGENT_VERSION:-3.29}
      - JENKINS_AGENT_WORKDIR=${JENKINS_AGENT_WORKDIR:-/var/jenkins}
      - JENKINS_HOSTNAME=${JENKINS_HOSTNAME}
      - JENKINS_SECRET=${JENKINS_SECRET}
      - JENKINS_SECRET_LIST=${JENKINS_SECRET_LIST}
      - JENKINS_URL=${JENKINS_URL}
      - JNLP_PROTOCOL_OPTS=${JNLP_PROTOCOL_OPTS}
    deploy:
      mode: global
    volumes:
      - ${DATADIR:-./jenkins}:${DATADIR}
    networks:
      - jenkins-privnet

  master:
    image: 'bitnami/jenkins:2'
    ports:
      - "8080:8080"
      - "8080:8080"
      - "8443:8443"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${JENKINS_MASTER_NODE}
    volumes:
      - ${JENKINS_MASTER_DATADIR:-/var/jenkins/jenkins-master-data}:/bitnami
    networks:
      - jenkins-privnet

networks:
  jenkins-privnet:
    driver: overlay
    external: true
